#Allowed time units are seconds, minutes, hours, days (and s, m, h, d). No unit will assume seconds
#The delay in between each regeneration task
regen-delay: '1h'

#Time to notify players before regeneration, 
warning-delay: '60s'
#Message to display before and after regeneration
#Players requires the following permissions to see messages: "worldrestoration.messages.getwarned" and "worldrestoration.messages.notifiedwhenfinished"
regen-warn-message: '&0[&4Server&0]&f: Starting world restoration in <delay> seconds.'
regen-done-message: '&0[&4Server&0]&f: Regeneration done!'

world-settings:
    world:
        #Should regeneration be enabled for this world?
        regen-enabled: false
        #After how long are blocks considered old and should be restored?
        considered-old-after: '14d'
        #How many blocks out from spawn (0,0,0) should be restored?
        #For better performance, this setting should not be set larger than the world radius
        radius: 30000
        #Should claims be protected from restoration? If set to false, claims will be regenerated!
        #This setting is ignored if none of the supported protection plugins are enabled
        respect-claims: true
    world_nether:
        regen-enabled: false
        considered-old-after: '14d'
        radius: 30000
        respect-claims: true
    world_the_end:
        regen-enabled: false
        considered-old-after: '14d'
        radius: 30000
        respect-claims: true

#-----------------------
#GriefDefender options
#-----------------------

#This option will allow the plugin to not restore claims
enable-griefdefender-support: true
#Number of blocks around claims that are not regenerated, set to 0 to disable
claim-settings:
    claim-padding: 10
    
#Config generated by plugin version. Do not change!
version: 1.0.1-alpha