#Allowed time units are seconds, minutes, hours, days (and s, m, h, d). No unit will assume seconds
#The delay in between each regeneration task
regen-delay: 1m

#Time to notify players before regeneration, 
warning-delay: 10s
#Message to display before regeneration
regen-message: "&0[&4Server&0]&f: Starting world restoration in <delay> seconds."
regen-done-message: "&0[&4Server&0]&f: Regeneration done!"

#-----------------------
#GriefDefender options
#-----------------------

#This option will allow the plugin to not restore claims
enable-griefdefender-support: true
#Number of blocks around claims that are not regenerated, set to 0 to disable
claim-settings:
    claim-padding: 10