name: WorldRestoration
version: 1.0.1-ALPHA
api-version: 1.15
author: Linoko
main: as.minecraft.worldrestoration.WorldRestoration
description: A plugin that regenerates the nature using CoreProtect.
depend: [CoreProtect]
softdepend: [GriefDefender]