/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package as.minecraft.worldrestoration;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
